### ISSUE TITLE
Preparing data and feeding as an input to train.py

### ISSUE THREAD

**Issue by behnazeslami** [akjindal53244/text_classification_hierarchical_cnn#1]
Actually I have some different datasets (as I've been attached them below) and I want to use your classification, but there's no manual for running train. Can you give an advice for running train and then running eval. 
For training how can I create my datasets and feed them as an input to train.py?

Thank you.
/Behnaz

[fashion_7000.txt](https://github.com/akjindal53244/text_classification_hierarchical_cnn/files/1539223/fashion_7000.txt)
[finance_7000.txt](https://github.com/akjindal53244/text_classification_hierarchical_cnn/files/1539225/finance_7000.txt)
[law_7000.txt](https://github.com/akjindal53244/text_classification_hierarchical_cnn/files/1539228/law_7000.txt)
[lifestyle_7000.txt](https://github.com/akjindal53244/text_classification_hierarchical_cnn/files/1539232/lifestyle_7000.txt)

**Comment by akjindal53244** [comment]
Hi Behnaz,
Thanks for pointing it out. I have added instructions.

Once you have train, valid, and test splits, put train.py into 'TRAIN' mode. Once training is completed, it will do evaluation on test data and will report accuracy and F1 score. Alternatively, you can load saved model and run 'train.py' in 'TEST' mode. Both should produce same results.

If you are stuck somewhere, let me know.

Thank you,
Ashvini
